name: 'ZCode IDE in Github Actions'
description: 'Start a Zcode IDE (on default port 3000)'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  ide-version:
    description: 'IDE version to use (default "latest")'
    required: false
    default: 'latest'
  ide-port:
    description: 'IDE port to use (default "3000")'
    required: false
    default: '3000'
  ide-network:
    description: 'IDE network to use (default "host")'
    required: false
    default: 'host'
  ide-container-name:
    description: 'IDE container name to use (default "test_container")'
    required: false
    default: 'test_container'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ide-version }}
    - ${{ inputs.ide-port }}
    - ${{ inputs.ide-network }}
    - ${{ inputs.ide-container-name }}